# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7780abf4355f08d03127779285add777e1f0001c03eb1ea01d3bc638ccaf5d3f8cf26aa8bf7e7c692d76d647ee2d8e00c3f5595298dd7f642c7d45189000d86

test:
  secret_key_base: a9d42e6c1179d9eb0a6c8c63e7dfd760587a1e3969c8d7dc57bf0fdabf184a8d2fa6b54574def87bec50eafc4940807fc8cbfb0dc51cce69491699797fb82b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
